### ISSUE TITLE
connecting to twitch irc chat

### ISSUE THREAD

**Issue by CanadianJeff** [Azelphur/SourceIRC#13]
is there support for this?

**Comment by Azelphur** [comment]
I haven't looked at the code base for a while, nor am I familiar with twitches IRC support. Is there anything special about connecting to Twitch vs any other IRC network?

**Comment by CanadianJeff** [comment]
actually I just got it to work it just needed the OAUTH in the password field in sourceirc.cfg it even joined the channel
